/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Product = IDL.Variant({
  'oemPrivateLabel' : IDL.Null,
  'hairBundles' : IDL.Null,
  'bulkSupply' : IDL.Null,
  'customWigs' : IDL.Null,
  'closuresAndFrontals' : IDL.Null,
});
export const QuoteRequest = IDL.Record({
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'companyName' : IDL.Text,
  'requirements' : IDL.Text,
  'product' : Product,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'getAllQuoteRequests' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
  'getBusinessHours' : IDL.Func(
      [],
      [
        IDL.Record({
          'saturday' : IDL.Text,
          'sunday' : IDL.Text,
          'mondayToFriday' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getContactInfo' : IDL.Func(
      [],
      [
        IDL.Record({
          'email' : IDL.Text,
          'phone' : IDL.Text,
          'location' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getQuoteRequest' : IDL.Func([IDL.Text], [QuoteRequest], ['query']),
  'getWhatsAppLink' : IDL.Func([], [IDL.Text], ['query']),
  'submitQuoteRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Product, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Product = IDL.Variant({
    'oemPrivateLabel' : IDL.Null,
    'hairBundles' : IDL.Null,
    'bulkSupply' : IDL.Null,
    'customWigs' : IDL.Null,
    'closuresAndFrontals' : IDL.Null,
  });
  const QuoteRequest = IDL.Record({
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'companyName' : IDL.Text,
    'requirements' : IDL.Text,
    'product' : Product,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'getAllQuoteRequests' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
    'getBusinessHours' : IDL.Func(
        [],
        [
          IDL.Record({
            'saturday' : IDL.Text,
            'sunday' : IDL.Text,
            'mondayToFriday' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getContactInfo' : IDL.Func(
        [],
        [
          IDL.Record({
            'email' : IDL.Text,
            'phone' : IDL.Text,
            'location' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getQuoteRequest' : IDL.Func([IDL.Text], [QuoteRequest], ['query']),
    'getWhatsAppLink' : IDL.Func([], [IDL.Text], ['query']),
    'submitQuoteRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Product, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };